### PR TITLE
Change color of link and button text in action bar above tables to have a better contrast ratio

### LINKED ISSUE #633: Light blue links and buttons are not contrasting enough
In idle (#3AA5EF) buttons and links have a contrast ratio of 2.68:1, oh hover it is 2.09:1.

Both are too weak.

### PR DESCRIPTION
**Pull request by rlucke**
Change color of link and button text to have a better contrast ratio.

Fixes #633

### CODE REVIEW

**Comment by ziegenberg** [comment]
Hi @rlucke,

thank you for your PR. Can you elaborate a little bit on what was done here? Also, see https://github.com/opencast/opencast-admin-interface/pull/645#issuecomment-2149967235 for reference.

**Comment by ziegenberg** [comment]
_Note: I changed the title for a better release note entry, as they are auto-generated._

**Comment by ziegenberg** [comment]
For reference,

before the fix:
Screenshot from 2024-06-05 21-19-01

after the fix:
Screenshot from 2024-06-05 21-19-10

**Review by ziegenberg — APPROVED** [review]
As soon as we have the ICLA, this can be merged.

**Comment by lkiesow** [comment]
We have an ICLA → merging

**Pull request merged**
