### PR TITLE
Change the color of placeholder text input and textarea fields to a darker gray

### LINKED ISSUE #632: Placeholders in the search field are too low-contrast
The placehoder text has a contrast of 2.43:1, that is far too little.

### PR DESCRIPTION
**Pull request by rlucke**
change color of placeholder text to a darker gray to have a better contrast ratio

Fixes #632

### CODE REVIEW

**Comment by ziegenberg** [comment]
Hi @rlucke,

thank you for your PR. Can you elaborate a little bit on what was done here? Also, see https://github.com/opencast/opencast-admin-interface/pull/645#issuecomment-2149967235 for reference.

**Comment by ziegenberg** [comment]
_Note: I changed the title for a better release note entry, as they are auto-generated._

**Comment by ziegenberg** [comment]
Before the fix:
Screenshot from 2024-06-05 21-48-18


After the fix:
Screenshot from 2024-06-05 21-48-59

**Review by ziegenberg — APPROVED** [review]
This is looking good. As soon as we have the ICLA, this can be merged.

**Comment by lkiesow** [comment]
We have the ICLA → Merging

**Pull request merged**
