### PR TITLE
Properly align wizard stepper labels

### LINKED ISSUE #485: Visual alignment of wizard steps
The steps in the add event wizard should be vertically aligned and centered on the horizontal line. They shouldn't look like this:

Screenshot from 2024-05-28 22-49-36

Here not even one of the step-circles is actually centered on the line.

### LINKED ISSUE #516: Visual Alignment for New Theme Wizard Steps and Buttons
Screenshot from 2024-06-04 08-51-43
Screenshot from 2024-06-04 08-40-31

### PR DESCRIPTION
**Pull request by JulianKniephoff**
Fixes #485.
Fixes #516.

### CODE REVIEW

**Comment by ziegenberg** [comment]
@JulianKniephoff do we also need to fix this in `src/components/shared/wizard/WizardStepperEvent.tsx` ?

**Comment by JulianKniephoff** [comment]
Here I was naively thinking that we would properly reuse code somewhere ...

**Review by ziegenberg — CHANGES_REQUESTED** [review]
I just checked, and this is fixed for creating a new series but not for creating new events.

**Comment by ziegenberg** [comment]
Sadly, `WizardStepperEvent.tsx` and `WizardStepper.tsx` do not share any code, though they probably should.

**Review by ziegenberg — APPROVED** [review]
Works now! :)

**Pull request merged**
