### PR TITLE
Fix big amount of eslint warnings

### PR DESCRIPTION
**Pull request by Arnei**
*includes https://github.com/opencast/opencast-admin-interface/pull/39, should only be merged after it.*

*Partially addresses #42*

Mostly fixes "react-hooks/exhaustive-deps" and "no-unused-vars".
Should be straightfoward.

### CODE REVIEW

**Comment by naweidner** [comment]
Found some more "no-unused-vars" and "react-hooks/exhaustive-deps"-warnings.
Is the main goal by now to eliminate ALL warnings or only reduce the amount of warnings?

eslint-warnings

**Comment by Arnei** [comment]
> Found some more "no-unused-vars" and "react-hooks/exhaustive-deps"-warnings. Is the main goal by now to eliminate ALL warnings or only reduce the amount of warnings?
> 
> eslint-warnings

Reduce the amount of warnings, by fixing the warnings that are easy to address. In my opinion, the rest warrants their own PRs, although it seems I have overlooked a `react-hooks/exhaustive-deps` :)

**Review by naweidner — APPROVED** [review]
> In my opinion, the rest warrant their own PRs

Agree :)

**Comment by Arnei** [comment]
Fixed the remaining exhaustive-deps warning

**Pull request merged**
