### PR TITLE
Fix filter functionality and performance

### LINKED ISSUE #211: [new Admin UI] filter function does not work properly yet
On the one hand, it takes time until the event or series I am looking for is displayed.

And on the other hand, nothing is shown to me when filtering, for example, if I have previously used pageing and, for example, had called up the second results page before the search.

**Environment Information**

OS: Debian bookworm
Browser: Firefox
Opencast version: 14.4

### PR DESCRIPTION
**Pull request by ferishili**
This PR fixes #211 and covers #577,

The filter functionality problem (on page > 1) has been solved by going to first page and load resources!

The performance issue has been solved by introducing debounce mechanism on loading resources.
This also covers Filter profiles!

### CODE REVIEW

**Comment by ferishili** [comment]
> in general fixed - just looks a little bit wobbly
> 
> grafik

Right, but the problem with datepicker in the filter was not covered by the initial issue #211,
Therefore, datepicker mispalcement needs to be fixed in a separate issue.

**Comment by ferishili** [comment]
https://github.com/opencast/opencast-admin-interface/issues/528 here is the issue regarding datepicker UI

**Comment by snoesberger** [comment]
Works mostly, but not if I'm using the start date as filter. If I go to page 3 and enter a start date filter, filtering is not working. In the browser console I do get the following error:
```
MUI X: A component is changing the uncontrolled value of a picker to be controlled.
Elements should not switch from uncontrolled to controlled (or vice versa).
Decide between using a controlled or uncontrolled valuefor the lifetime of the component.
The nature of the state is determined during the first render. It's considered controlled if the value is not `undefined`.
More info: https://fb.me/react-controlled-components
```

**Comment by ferishili** [comment]
Thanks for the testing and your feedback, I will fix it right away

**Comment by ferishili** [comment]
As an info, this error also happens in the current main branch, therefore, it would say, it is separate issue!

**Comment by ferishili** [comment]
Fix for MUI error is available in #652

**Comment by lkiesow** [comment]
Probably makes sense to merge https://github.com/opencast/opencast-admin-interface/pull/654 first

**Comment by Arnei** [comment]
All other concerns seem to have been addressed (or moved), so I'll be merging this.

**Pull request merged**
