### PR TITLE
Add system type dropdown in adopter registration

### PR DESCRIPTION
**Pull request by dennis531**
Screenshot:
image

Related Opencast PR: opencast/opencast#6058

### CODE REVIEW

**Comment by dennis531** [comment]
Example:
image
image

@luniki Did you imagine something like this?

**Comment by lkiesow** [comment]
Yes, that looks great.

**Comment by Arnei** [comment]
Quick local test confirms that this works.

I am undecided about whether I like the dropdown style. It does not look, but decidedly different from our other dropdowns. What do you think about bringing it more in line with our other dropdowns, stylistically?

**Review by Arnei — APPROVED** [review]

**Review by gregorydlogan — APPROVED** [review]
Works as expected, even if https://github.com/opencast/adopter-registration-server/pull/80 isn't deployed yet.

**Pull request merged**
