### PR TITLE
Fix misplaced themes details menu navigation buttons

### LINKED ISSUE #551: Misplaced themes details menu navigation buttons
In Themes details, the navigation buttons are not in place!

In local
Screenshot 2024-06-04 at 12 03 57

on https://develop.opencast.org/
Screenshot 2024-06-04 at 12 06 02

### PR DESCRIPTION
**Pull request by dennis531**
image

Closes #551

### CODE REVIEW

**Comment by ferishili** [comment]
@dennis531 would that be also good to nowrap the text in the nav items? In this way it looks even better. What do you think?

**Comment by dennis531** [comment]
> @dennis531 would that be also good to nowrap the text in the nav items? In this way it looks even better. What do you think?


`white-space: nowrap;` causes long texts to become completely invisible. I would suggest min-width as an alternative.

**Comment by reiferschris** [comment]
There is still a continuous line below the "arrow" that points to the current tab that doesn't exist on the old admin-ui.

**Comment by dennis531** [comment]
Solution with min-width:
image

**Comment by ziegenberg** [comment]
I like the `min-width` solution 👍🏻

**Comment by Arnei** [comment]
Looks like people are happy with this, merging.

**Pull request merged**
