### PR TITLE
Port Tobira integration

### LINKED ISSUE #311: Tobira Integration
https://github.com/opencast/opencast/pull/4131 added Tobira integration to the old admin UI. This should be forward-ported.

There might also be some future requirements that can be tracked here.

See also:

* https://github.com/elan-ev/tobira/issues/718
* https://github.com/elan-ev/tobira/issues/719

### PR DESCRIPTION
**Pull request by Arnei**
Resolves #311

The old admin ui had an integration for tobira in the series details and new series modal. This ports the integration to our new ui. The user experience could arguably be improved upon, but this should work and be familiar to users who already used the integration in the old admin ui.

### CODE REVIEW

**Comment by Arnei** [comment]
Ready for review! (...as soon as I fix the merge conficts I guess)

**Comment by KatrinIhler** [comment]
Without configuring a Tobira for my Opencast installation I get

grafik

Otherwise I still gotta figure out how to easily test this locally.

**Review by KatrinIhler — CHANGES_REQUESTED** [review]
Conflicts fixed, see: https://github.com/KatrinIhler/opencast-admin-interface/tree/pr313-conflicts-fixed

The error for a non-working Tobira connection should appear in the Tobira tab, not the access tab, like in the old UI (see also comment above).

Minor differences in style between the two UIs (new one on the left), note the missing space between the table and the text above.

grafik

Obscure bug: The path is always one letter behind the one entered in the text field. (see text below and summary).
grafik

Apart from the fact that I can't figure out how to select existing pages (in the old and the new UI, but maybe it's because they aren't empty?) and the issues mentioned above, it looks fine.

**Comment by Arnei** [comment]
> Apart from the fact that I can't figure out how to select existing pages (in the old and the new UI, but maybe it's because they aren't empty?) and the issues mentioned above, it looks fine.

The name of a selectable page is written in bold. In the image below I have selected "Athena Lecture"? (What makes a page selectable? Beats me.)

Bildschirmfoto vom 2024-06-20 12-00-35

**Review by owi92 — APPROVED** [review]
This is working and a clear improvement, and not breaking anything as far as I can tell.

There are some additional features that were requested in https://github.com/opencast/opencast-admin-interface/issues/311 after this was already finished and that I will be working on, but their omission shouldn't block merging what's already here.

**Comment by Arnei** [comment]
Thanks for the review @owi92. There were some merge conflicts since your review, would you mind quickly checking again if this still works to your satisfaction?

**Comment by owi92** [comment]
Yes, still appears to be working 👌
Though I noticed a couple of things I must have missed yesterday.
- when creating a new series, I get this note (which is true, but probably not necessary at this point):
Bildschirmfoto 2024-07-24 um 11 53 35

- the link button is a little too close to the link text: 
Bildschirmfoto 2024-07-24 um 11 58 26

If you want you can still fix those, but I don't see them as blockers and I can also do that in my upcoming pull request.

**Comment by Arnei** [comment]
> when creating a new series, I get this note (which is true, but probably not necessary at this point):

Seen that elsewhere, like not a cause of this PR.

> the link button is a little too close to the link text

Would be great if you could fix that.

**Comment by Arnei** [comment]
Merging this even though there is still a requested change, as following reviews have approved this PR and it is already being used in #878.

**Pull request merged**
