### PR TITLE
Hide tooltip on hover

### LINKED ISSUE #722: Tooltip for main menu items covers other main menu item
If I am hovering "Systems", but then decide I want to go to "Capture" after all, I
- Need to know it is there, as the tooltip is hiding the icon
- Need to make the tooltip go away to be able to click on the icon (clicking on the tooltip does the same as clicking on the item it belongs to)

Bildschirmfoto vom 2024-06-20 15-34-00

### PR DESCRIPTION
**Pull request by dennis531**
Close #722

### CODE REVIEW

**Comment by Arnei** [comment]
Might not be the best way to go about this. In the editor, tooltips explicitly do not disappear even if you click on them, allowing you to mark the contents. Iirc this was done for usability and accessibility reasons which should also be important to us here in the admin ui.

**Review by lkiesow — CHANGES_REQUESTED** [review]
-1 to this solution. Having non-interactive tooltips is bad for accessibility. In particular, trying to use this in combination with screen magnifications is bad. A simple alternative solution for #722 would be `placement='right'`.

**Comment by dennis531** [comment]
Thanks for the suggestion. The main navigation tooltips are placed on the right side. I hope this improves the usability.

**Comment by lkiesow** [comment]
Looks good

**Pull request merged**
