### PR TITLE
fix a11y issues in header nav

### LINKED ISSUE #601: Language selector is not accessible with the keyboard
You cannot set the language using the keyboard. The element cannot be accessed using the keyboard. If the drop-down menu is open, a language can be selected.

### LINKED ISSUE #603: Elements in the header are not recognizable in case of language output
The Opencast logo, which is supposed to be the home button, is read out as “link Opencast logo”, so what the link does is not recognizable.
The media module and studio buttons are only read out as “link”.

### LINKED ISSUE #605: Some elements in the header cannot be reached with the keyboard
- System warnings and notifications
- Help
- User menu

### PR DESCRIPTION
**Pull request by rlucke**
use button tag instead of div
reorder tooltip
add some css changes to keep layout

fixes #605 
fixes #601 
fixes #603

### CODE REVIEW

**Review by Arnei — APPROVED** [review]
Can navigate to all buttons in the header via tabbing now, and layout is kept. Nice.

**Comment by Arnei** [comment]
As a note, adding translations in PR has no effect, as crowdin can and will override any changes not made directly to the "source" file (lang-en_US.json). If you would like to help with translations, please request access to our crowdin project at [crowdin.com/project/opencast-admin-interface](https://crowdin.com/project/opencast-admin-interface).

**Comment by Arnei** [comment]
Also this is probably obvious, but I do not understand how this addresses #603. Could you explain?

**Comment by rlucke** [comment]
> Also this is probably obvious, but I do not understand how this addresses #603. Could you explain?

The correct position of the ToolTip in the template enables the screenreader to say more than just "link".

**Pull request merged**
