### PR TITLE
Fix button misplacmenet in the comment section and cleanup css

### LINKED ISSUE #540: Misplaced submit button in Event Details -> Comments section
The submit button is off!
Under Event -> Details -> Comments

Screenshot 2024-06-04 at 11 33 40

### PR DESCRIPTION
**Pull request by marwyg**
Fixes #540 

This PR adds some CSS flex to rearrange the button and the selectbox. Furthermore it cleans up some css that seem to have no effect and makes the selectbox a little bit larger (because why not, there is plenty of room).

### CODE REVIEW

**Comment by jduehring** [comment]
Looks good to me and works as expected.

**Comment by marwyg** [comment]
My removed CSS seems to break the view, when you click on "reply". See #526 as reference. I will make another commit for this PR here to enhance styling of the "reply" view.

**Comment by marwyg** [comment]
I kept the big checkbox against this comment: https://github.com/opencast/opencast-admin-interface/issues/527#issue-2332984970 because of accessibility reasons. What do you think?

Nonetheless, the reply view looks like this now:
grafik

**Comment by marwyg** [comment]
It's ready for review

**Comment by marwyg** [comment]
I thought about this. But I am not sure if I might break something and I found out, that it's possible to change order with CSS ;) But if you prefer the other way I try it out.

**Comment by Arnei** [comment]
I would avoid ordering with CSS unless necessary in order to keep with convention and keep it simple.

**Comment by marwyg** [comment]
I reordered the elements in the TSX now.

**Review by Arnei — APPROVED** [review]

**Pull request merged**
